# -*- coding: utf-8 -*-
"""INDEX.md is DERIVED from the dropbox directory, never hand-rewritten. Audit 09-14 item 9.

WHAT HAPPENED. The auditor wrote their INDEX entry for the 09-14 audit, verified it, and then
"it was clobbered by a concurrent builder rewrite of INDEX.md inside the hour" -- me, prepending
my own line from a copy I had read before theirs landed. Their words: this is "the same
two-writers-one-file failure as the four defects above, in our own coordination channel, and it
means an audit finding can silently disappear between the write and the read."

IT IS WORSE THAN THEY KNEW. On 2026-09-14 the directory held 146 notes and INDEX.md listed 90.
FIFTY-SIX notes were missing, including both of my own from that day. Every hand-rewrite since
the file was created has been an opportunity to drop a line, and the drift had been accumulating
silently because nothing ever compared the index to the directory.

THE FIX, which is the auditor's own second suggestion. Each party writes only its own dated
note file -- a thing nobody else touches -- and INDEX.md is GENERATED from the directory. Two
writers can no longer collide, because there is nothing shared to collide over. Hand-written
summaries already in the index are preserved verbatim; anything new gets a summary derived from
its own first substantive line, which the author can then improve in place.

    python build_dropbox_index.py [--check]

--check exits 1 without writing if the index is not what the directory implies (that is what
tests/test_dropbox_index_complete.py runs in CI).
"""
import argparse
import glob
import io
import os
import re
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
DROP = os.path.join(HERE, "odin_cowork_dropbox")
INDEX = os.path.join(DROP, "INDEX.md")
ENTRY = re.compile(r"^- \*\*(?P<label>.+?)\*\*\s+[—-]\s+`(?P<file>[^`]+\.md)`\s+[—-]\s+"
                   r"(?P<summary>.*)$")
DATE = re.compile(r"^(\d{4}-\d{2}-\d{2})([a-z]?)")

HEADER = """<!-- GENERATED by build_dropbox_index.py -- do not hand-edit.

     Audit 09-14 item 9. This file used to be rewritten by hand by whoever wrote last, from a
     copy read before the other party's entry landed, and entries were silently lost: on
     2026-09-14 the directory held 146 notes and this index listed 90.

     Write your note as its own dated file and run `python build_dropbox_index.py`. The index is
     rebuilt from the directory, so two writers cannot clobber each other. To improve an entry's
     one-line summary, edit the line here and re-run: existing summaries are preserved. -->

"""


def label_for(fn):
    m = DATE.match(fn)
    d = (m.group(1) + m.group(2)) if m else "?"
    rest = fn[len(d):].lstrip("_-").rsplit(".md", 1)[0]
    kind = "BUILDER" if "BUILDER" in rest.upper() else (
        "audit" if "audit" in rest.lower() else "note")
    pretty = rest.replace("_", " ").strip()
    pretty = re.sub(r"^(BUILDER|ACK)\s*", "", pretty, flags=re.I).strip()
    return f"{d} {kind}" + (f" ({pretty[:70]})" if pretty else "")


def summary_for(path):
    """First substantive sentence of the note, for a file the index has never seen."""
    try:
        txt = io.open(path, encoding="utf-8", errors="replace").read()
    except Exception:  # noqa: BLE001
        return "(unreadable)"
    txt = re.sub(r"^---.*?^---", "", txt, flags=re.S | re.M)
    for line in txt.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("|") or s.startswith("```"):
            continue
        s = re.sub(r"[*`_]", "", s).strip()
        if len(s) < 25:
            continue
        return (s[:240] + ("…" if len(s) > 240 else ""))
    return "(no summary yet -- edit this line in INDEX.md and re-run the generator)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    known = {}
    order_label = {}
    if os.path.exists(INDEX):
        for line in io.open(INDEX, encoding="utf-8", errors="replace"):
            m = ENTRY.match(line.rstrip("\n"))
            if m:
                known[m.group("file")] = m.group("summary").rstrip()
                order_label[m.group("file")] = m.group("label")

    files = sorted(os.path.basename(p) for p in glob.glob(os.path.join(DROP, "*.md"))
                   if os.path.basename(p) != "INDEX.md")

    missing = [f for f in files if f not in known]
    orphan = [f for f in known if f not in files]

    def sort_key(fn):
        m = DATE.match(fn)
        return ((m.group(1) if m else "0000-00-00"), (m.group(2) if m else ""), fn)

    lines = [HEADER]
    for fn in sorted(files, key=sort_key, reverse=True):
        lines.append(f"- **{order_label.get(fn) or label_for(fn)}** — `{fn}` — "
                     f"{known.get(fn) or summary_for(os.path.join(DROP, fn))}")
    out = "\n".join(lines) + "\n"

    if a.check:
        cur = io.open(INDEX, encoding="utf-8", errors="replace").read() \
            if os.path.exists(INDEX) else ""
        if missing or orphan or cur != out:
            print(f"INDEX is not what the directory implies: {len(missing)} note(s) missing, "
                  f"{len(orphan)} entry(ies) with no file.")
            for f in missing[:12]:
                print(f"   MISSING  {f}")
            for f in orphan[:6]:
                print(f"   ORPHAN   {f}")
            print("   Run: python build_dropbox_index.py")
            return 1
        print(f"OK -- INDEX lists all {len(files)} dropbox note(s)")
        return 0

    io.open(INDEX, "w", encoding="utf-8").write(out)
    print(f"INDEX.md rebuilt from the directory: {len(files)} note(s) "
          f"({len(missing)} newly added, {len(orphan)} stale entry(ies) dropped)")
    for f in missing[:20]:
        print(f"   + {f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
