# -*- coding: utf-8 -*-
"""relabel_price_only.py -- stop rendering unverified outcomes in the language of verified ones.

This is the root cause of the false SELLAS CRL. 307 decision pages are generated by the price-only
tier, which infers an outcome from the stock reaction around a date rather than reading a filing.
They were already noindex, and excluded from the sitemap, which was the right instinct. But they
still carried:

    <title>SLS FDA Decision 2025-02-20: CRL</title>
    <h1>SLS FDA Decision CRL - 2025-02-20</h1>
    <span class="badge crl">X CRL</span>

which is exactly how a verified, primary-sourced decision is rendered. A reader, a scraper, or an
AI assistant reading that page has no way to tell it apart from a fact. Being noindex does not help
any of them, because the pages are still live and still linked from /decisions.

So: keep the data, change the claim. The page now says what it actually knows, which is that the
price behaved consistently with an outcome and nobody has checked a filing.

    python relabel_price_only.py [--dry-run]
"""
import argparse, glob, os, re, sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(HERE, "pdufa_site_src")

BANNER = (
    '<div style="background:rgba(240,200,106,.09);border:1px solid #6b5a2f;border-radius:10px;'
    'padding:12px 14px;margin:14px 0;font-size:13.5px;line-height:1.6;color:#e8d9a8">'
    '<b>Unverified record.</b> The outcome below was <b>inferred from the share-price reaction</b> '
    'around this date. Nobody has confirmed it against an FDA, SEC or company document, and it may '
    'be wrong: we have published at least one inferred outcome that turned out to be impossible '
    '(see <a href="/corrections" style="color:#f0c86a">corrections</a>). Treat it as a price '
    'observation, not as a regulatory fact. Verified decisions on this site always link a primary '
    'source.</div>')


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    changed = skipped = 0
    for p in sorted(glob.glob(os.path.join(SITE, "fda-decision", "*", "index.html"))):
        t = open(p, encoding="utf-8", errors="replace").read()
        if "price-only" not in t:
            skipped += 1
            continue
        o = t
        slug = os.path.basename(os.path.dirname(p))

        # 1. title / og:title: no verdict in the headline
        t = re.sub(r"(<title>[A-Z]+ FDA Decision \d{4}-\d{2}-\d{2}): (Approved|CRL)( \| pdufa\.bio</title>)",
                   r"\1: outcome unverified\3", t)
        t = re.sub(r'(content="[A-Z]+ FDA Decision \d{4}-\d{2}-\d{2}): (Approved|CRL)( \| pdufa\.bio")',
                   r"\1: outcome unverified\3", t)

        # 2. h1
        # actual markup is: <h1>ABBV FDA Decision <span class="g">Approved</span> - 2025-04-02</h1>
        t = re.sub(r'(<h1>[A-Z]+ FDA [Dd]ecision )<span class="g">(?:Approved|CRL)</span>',
                   r'\1<span class="g" style="color:#f0c86a">outcome unverified</span>', t)

        # 3. the outcome badge: say what we actually know
        t = t.replace('<span class="badge app">&#10003; Approved</span>',
                      '<span class="badge amb">Unconfirmed &middot; price consistent with approval</span>')
        t = t.replace('<span class="badge app">✓ Approved</span>',
                      '<span class="badge amb">Unconfirmed &middot; price consistent with approval</span>')
        t = t.replace('<span class="badge crl">&#10007; CRL</span>',
                      '<span class="badge amb">Unconfirmed &middot; price consistent with a CRL</span>')
        t = t.replace('<span class="badge crl">✗ CRL</span>',
                      '<span class="badge amb">Unconfirmed &middot; price consistent with a CRL</span>')

        # 4. meta description
        t = re.sub(r'(content="On \d{4}-\d{2}-\d{2} the FDA decision for [A-Z]+ \([^)]*\) was )'
                   r'(Approved|CRL)\.', r"\1not verified against a primary source.", t)

        # 5. visible banner, once, above the first card
        if "Unverified record." not in t:
            m = re.search(r'<div class="wrap">|<main[^>]*>', t)
            if m:
                t = t[:m.end()] + BANNER + t[m.end():]

        if t != o:
            changed += 1
            if not a.dry_run:
                open(p, "w", encoding="utf-8").write(t)

    print(f"{'would relabel' if a.dry_run else 'relabelled'} {changed} price-only decision page(s); "
          f"{skipped} sourced page(s) untouched")


if __name__ == "__main__":
    main()
