# -*- coding: utf-8 -*-
"""CI guard: INDEX.md lists every note in the dropbox. Audit 09-14 item 9.

The auditor wrote their INDEX entry for the 09-14 audit, verified it, and watched it vanish
inside the hour under a builder rewrite from a copy held before theirs landed. Their framing is
the one that matters: "this is the same two-writers-one-file failure as the four defects above,
in our own coordination channel, and it means an audit finding can silently disappear between
the write and the read."

It had been happening for months. When this guard was written the directory held 146 notes and
INDEX.md listed 90: FIFTY-SIX missing, including both builder notes from that same day. Nothing
had ever compared the index to the directory, so every hand-rewrite was a chance to drop a line
and no one could tell.

INDEX.md is generated by build_dropbox_index.py now. This asserts the generated file is current,
which is the same thing as asserting that nobody has hand-edited it into disagreement with the
directory.

    python tests/test_dropbox_index_complete.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    gen = os.path.join(HERE, "build_dropbox_index.py")
    if not os.path.exists(gen):
        print("  SKIP build_dropbox_index.py not found")
        return 0
    p = subprocess.run([sys.executable, gen, "--check"], cwd=HERE,
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    out = (p.stdout or "").strip()
    print("  " + "\n  ".join(out.splitlines()[:16]) if out else "")
    if p.returncode != 0:
        print("\n  A note that is not in the index is a note nobody will read. "
              "DO NOT PUBLISH.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
